version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "linkuptrigger"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1dcrjqw5pytf5"
s3_prefix = "linkuptrigger"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
